jobs: 10
jobname: "{rule}.{jobid}"
cluster: "sbatch -t {resources.maxtime} --partition=standard --mem={resources.mem_mb} -c {resources.cpus} --output=log_{rule}_%j.out --mail-type=FAIL"
default-resources: [cpus=1, time_min=240]
max-jobs-per-second: 5
max-status-checks-per-second: 20
restart-times: 5
rerun-incomplete: True
latency-wait: 60